ESA-VirES/VirES

scripts/scripts.d/25_allauth_install.sh, scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
* Added django-countries app (Need to run fabric installer for different environments!)
* Added some social provider specific settings to request more user data
* Moved eoxs_allauth to top of installed apps to make sure correct templates are laoded;
=> User extension with Profile

scripts/devel.d/25_requestlogging_install.sh, scripts/install.d/25_requestlogging_install.sh, scripts/production.d/25_requestlogging_install.sh, scripts/scripts.d/25_requestlogging_install.sh, scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh, scripts/scripts.d/55_client_config.sh, scripts/scripts.d/56_client_install_static.sh
This is counterpart of https://github.com/ESA-VirES/VirES-Server/pull/17
=> Access logging configuration.

scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
This is counterpart of https://github.com/ESA-VirES/VirES-Server/pull/20
=> eoxs_allauth review

scripts/scripts.d/20_django.sh, scripts/scripts.d/50_eoxs_instance_production.sh
Needed for django error reporting via mail
=> New eox instance conf vars

tests/test_models.py, tests/wps_util.py
=> MIO model fix

tests/test_models.py
Adapting WPS integration tests to https://github.com/ESA-VirES/MagneticModel/pull/17 and https://github.com/ESA-VirES/VirES-Server/pull/93
=> Adapting WPS integration tests

scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
Adding collection to spacecraft mapping for the new Swarm EFIx_LP products.
Tested on testing.
=> EFIx_LP Support

scripts/devel.d/21_ply.sh, scripts/install.d/21_ply.sh, scripts/production.d/21_ply.sh, scripts/scripts.d/21_ply.sh, scripts/scripts.d/30_eoxmagmod_sdist.sh, scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
- one new dependency
- modified instance configuration
- removal of no longer used registered models
=> Model composition

scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
configuration changes needed by https://github.com/ESA-VirES/VirES-Server/pull/105
=> EEF extra sampling and TEC sample grouping configuration

scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
Configuration changes required by https://github.com/ESA-VirES/VirES-Server/pull/111.
=> Token authentication

scripts/install.sh, scripts/lib_common.sh, scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh, scripts/scripts.d/60_client_config.sh
- Custom data upload configuration changes
=> Data upload

scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
related to https://github.com/ESA-VirES/WebClient-Framework/pull/339 and https://github.com/ESA-VirES/VirES-Server/pull/118
=> Workspace URL configuration.

scripts/scripts.d/30_eoxmagmod_sdist.sh, tests/test_models.py
implementing changes requested by https://github.com/ESA-VirES/WebClient-Framework/issues/352
=> Revised magnetic models

scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
- updated collection to satellite mapping configuration
=> Server-side IPDxIRR product support

scripts/scripts.d/50_p36_oauth_instance.sh, scripts/scripts.d/50_p36_oauth_instance_production.sh
configuration changes required by https://github.com/ESA-VirES/VirES-Server/pull/129
=> Hotfix: OAuth server logging

scripts/install.sh, scripts/jhub.d/15_npm.sh, scripts/jhub.d/17_jhub_pip_upgrade.sh, scripts/jhub.d/20_jhub_jupyterhub.sh, scripts/jhub.d/26_jhub_oauthenticator.sh, scripts/jhub.d/30_jhub_vires_jhub.sh, scripts/jhub.d/50_jhub_instance.sh, scripts/jhub.d/80_jhub_vagrant_init.sh, scripts/jhub_venv_execute.sh, scripts/jhub_venv_python.sh, scripts/scripts.d/30_jhub_vires_jhub.sh, scripts/scripts.d/50_jhub_instance.sh, scripts/scripts.d/56_client_install.sh, scripts/scripts.d/80_jhub_vagrant_init.sh, scripts/scripts.d/99_restart_server.sh, vagrant/Vagrantfile
- Vagrant JHub installation
- custom VRE style configuration
=> VRE styling

scripts/scripts.d/50_eoxs_instance.sh, scripts/scripts.d/50_eoxs_instance_production.sh
Key Feature:
- configuration of the required VirES permission
- reviewed URL patterns configuration
required by https://github.com/ESA-VirES/VirES-Server/pull/136
=> Proper VirES-Server authorization.

scripts/jhub.d/30_jhub_viresclient.sh, scripts/scripts.d/30_jhub_viresclient.sh, scripts/scripts.d/50_jhub_instance.sh, scripts/scripts.d/51_eoxs_instance.sh, scripts/scripts.d/51_eoxs_instance_production.sh, vagrant/Vagrantfile
- minor configuration changes
see related https://github.com/ESA-VirES/VirES-Server/pull/151
=> VRE initialization

scripts/scripts.d/51_eoxs_instance.sh, scripts/scripts.d/51_eoxs_instance_production.sh
Configuration changes required by https://github.com/ESA-VirES/VirES-Server/pull/160
=> VIR-350: new fieldlines API

preprocessing/repack_vobs.py, preprocessing/test_repack_vobs.py, registration/register_data.sh
see related https://github.com/ESA-VirES/VirES-Server/pull/162
=> Support scripts for the Virtual Observatories products.

preprocessing/average_omni_hr_1min.py, preprocessing/common.py, preprocessing/compare_cdf.py, preprocessing/convert_aej_pb.py, preprocessing/fix_array_dimensions.py, preprocessing/fix_efi_lp_u_orbit.py, preprocessing/repack_aux_obs.py, preprocessing/repack_vobs.py, preprocessing/test_convert_aej_pb.py, preprocessing/test_repack_aux_obs.py, preprocessing/test_repack_vobs.py, registration/register_data.sh, scripts/lib_common.sh, scripts/lib_postgres.sh, scripts/scripts.d/11_rpm_repos_postgresql.sh, scripts/scripts.d/25_oauth_django_allauth.sh, scripts/scripts.d/35_eoxs_wps_async_sdist.sh, scripts/scripts.d/51_eoxs_instance.sh, scripts/scripts.d/51_eoxs_instance_production.sh, scripts/scripts.d/60_client_config.sh
Key features:
- upgrade to PG12
- AUX_OBSH2 configuration
- upgrade of the async. WPS backend
- reviewed per-processing scripts
related to https://github.com/ESA-VirES/VirES-Server/pull/164
=> production release (VirES v3.5.0)

scripts/scripts.d/51_eoxs_instance.sh, scripts/scripts.d/51_eoxs_instance_production.sh
required by https://github.com/ESA-VirES/VirES-Server/pull/172
=> Swarm-A/B conjunctions - configuration

scripts/scripts.d/51_eoxs_instance.sh, scripts/scripts.d/51_eoxs_instance_production.sh
related to https://github.com/ESA-VirES/VirES-Server/pull/181
=> Heliophysics API configuration

README.md, preprocessing/compare_cdf.py, registration/register_data.sh, scripts/devel.d/31_eoxs_vires_sync_devel.sh, scripts/install.d/31_eoxs_vires_sync.sh, scripts/scripts.d/20_eoxs_jsonschema.sh, scripts/scripts.d/20_eoxs_pyyaml.sh, scripts/scripts.d/20_oauth_jsonschema.sh, scripts/scripts.d/20_oauth_pyyaml.sh, scripts/scripts.d/25_oauth_django_oauth.sh, scripts/scripts.d/31_eoxs_vires_sync.sh, scripts/scripts.d/31_eoxs_vires_sync_devel.sh, scripts/scripts.d/51_eoxs_instance.sh, scripts/scripts.d/51_eoxs_instance_production.sh, vagrant/Vagrantfile
configuration changes related to https://github.com/ESA-VirES/VirES-Server/pull/187
=> production release (VirES v3.9.0)

registration/register_data.sh
related to https://github.com/ESA-VirES/VirES-Server/pull/188
=> Support for GOCE MAG products

registration/register_data.sh
- Vagrant: registration of EFIxIDM products
related to https://github.com/ESA-VirES/VirES-Server/pull/189
=> Support for SW_EFIxIDM_2_ products

registration/register_data.sh, scripts/scripts.d/30_eoxs_eoxmagmod_sdist.sh
Configuration changes related to https://github.com/ESA-VirES/VirES-Server/pull/191
=> production release (VirES v3.10.0)
